INSERT INTO campaign (
    title,
    company_name,
    benefit,
    description,
    recruit_start_date,
    recruit_end_date,
    recruit_count,
    apply_url,
    thumbnail_url,
    region,
    platform,
    category,
    view_count,
    favorite_count,
    status,
    created_at,
    updated_at
) VALUES
(
    '강서구 파스타 맛집 체험단',
    '오브키친',
    '2인 식사권',
    '서울 강서구 파스타 매장 방문 후 블로그 리뷰를 작성하는 체험단입니다.',
    '2026-07-04',
    '2026-07-14',
    10,
    'https://example.com/campaigns/1',
    'https://images.unsplash.com/photo-1473093295043-cdd812d0e601',
    '서울 강서구',
    '블로그',
    '맛집',
    253,
    18,
    'OPEN',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '부산 호텔 숙박 체험단',
    '해운스테이',
    '1박 숙박권',
    '부산 해운대 숙소를 체험하고 인스타그램 콘텐츠를 업로드하는 체험단입니다.',
    '2026-07-04',
    '2026-07-20',
    5,
    'https://example.com/campaigns/2',
    'https://images.unsplash.com/photo-1566073771259-6a8506099945',
    '부산 해운대구',
    '인스타그램',
    '숙박',
    132,
    11,
    'OPEN',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

